### ISSUE TITLE
Type conflict with @types/amplitude

### ISSUE THREAD

**Issue by calvinkcox-divvyhomes** [amplitude/experiment-js-client#17]
Due to a namespace declaration there is currently a conflict in typing between @types/amplitude and this library. I see this has been removed in both #15 and #16 but am curious if there will be a released fix soon. This is preventing our application from building correctly.

See:
```
node_modules/@amplitude/experiment-js-client/dist/types/src/integration/amplitude.d.ts:5:9 - error TS2403: Subsequent variable declarations must have the same type.  Variable 'amplitude' must be of type 'typeof import(".../node_modules/@types/amplitude-js/index")', but here has type 'any'.

5     var amplitude: any;
          ~~~~~~~~~

  node_modules/@types/amplitude-js/index.d.ts:8:1
    8 export as namespace amplitude;
      ~~~~~~
    'amplitude' was also declared here.
```

**Comment by calvinkcox-divvyhomes** [comment]
@bgiori not sure if you are already aware of this and that was driving your PRs or if there is an obvious work-around.
Thanks for any assistance.

**Comment by calvinkcox-divvyhomes** [comment]
A solution for anyone else running into problem. You can disable lib checks via your `tsconfig` file:
https://www.typescriptlang.org/tsconfig#skipLibCheck

This will resolve the issue. I wouldn't recommend it as you are basically ignoring typing in all dependencies.

**Comment by bgiori** [comment]
Hi @calvinkcox-divvyhomes 

thanks for this report. Will push out a fix.

**Comment by bgiori** [comment]
This issue should be fixed in `v1.3.3`. Thanks again for the report, feel free to close the issue once you have verified the new version.

**Comment by calvinkcox-divvyhomes** [comment]
@bgiori I am still having an issue (although slightly different than the original). Given the following:
```
amplitude.getInstance().init(key, {},
  (amplitudeClient) => {
    const experiment = Experiment.initialize(key,
        userProvider: new AmplitudeUserProvider(amplitudeClient),
        analyticsProvider: new AmplitudeAnalyticsProvider(amplitudeClient),
      },
    );
  },
);
```

Causes an error where `amplitudeClient` is of type `AmplitideClient` brought in from `@types/amplitude-js` where `AmplitudeUserProvider` is expecting an `AmplitudeInstance` from `@amplitude/experiment-js-client`

I know there is also the `experiment.setUserProvider()` (deprecated), but that also relies on `new AmplitudeUserProvider()` which would circle back around to this same issue.

I can override types and get this out, but curious your thoughts.

**Comment by calvinkcox-divvyhomes** [comment]
Double checking your changes against the error codes I believe the error was created by implementing `_logEvent` in [here](https://github.com/amplitude/experiment-js-client/pull/20/files#diff-8010aa1a2b16faea06b51afa23ce7d91fd6d506ebbd72a30809cfd9e98dd585bR17). The type names shouldn't matter, but the `AmplitudeClient` type doesn't have that method.

**Comment by bgiori** [comment]
@calvinkcox-divvyhomes I am unable to reproduce this error. Would you be able to post the exact build failure?

**Comment by bgiori** [comment]
Accidentally closed, reopened. Please double check this fixes the issue for you and I can close for real

**Comment by calvinkcox-divvyhomes** [comment]
@bgiori issue resolve. Thanks for taking the time to deal with this.
